name: Test Build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test-linux:
    name: Test Linux Build
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}

    strategy:
      matrix:
        include:
          - GRADLE_ARCH: amd64
            RUNS_ON: ubuntu-22.04
            JAVA_VERSION: 21

    runs-on: ${{ matrix.RUNS_ON }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Shaded JAR
        run: ./gradlew clean build

      - name: Build JPackage Binary
        run: ./gradlew jpackage

